import streamlit as st
from fpdf import FPDF

# 工业级 PDF 报告生成类
class AuditReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(190, 10, "Tax Audit Summary (Bilingual Report) 2026", ln=True, align="C")
        self.ln(10)

def create_pdf_report(income, audit_results):
    pdf = AuditReport()
    pdf.add_page()
    
    # 1. Household Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(190, 10, "SECTION 1: Household Overview (Jia Ting Gai Kuang)", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(190, 8, f"Reported Income (MAGI): ${income:,}", ln=True)
    pdf.ln(5)
    
    # 2. Detailed Audit Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(190, 10, "SECTION 2: AI Brokerage Audit (Zhi Neng Shen Ji Detail)", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    if audit_results:
        for res in audit_results:
            # 自动处理字符，确保安全输出
            pdf.multi_cell(190, 8, f"- {str(res)}")
    else:
        pdf.cell(190, 8, "No risks identified (Wei Fa Xian Xian Zhu Feng Xian).", ln=True)
        
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(190, 5, "Notice: This report is generated by AI based on 2026 tax codes.\nMian Ze Sheng Ming: Ben bao gao jin gong can kao.")
    return pdf.output(dest='S')

# --- UI 界面 (已根据你的截图完美对齐) ---
st.set_page_config(page_title="华人报税助手 Pro", layout="wide")
st.title("🚀 华人报税助手 Pro (2026 报告版)")
st.subheader("Chinese Tax Assistant Pro - 2026 Report Edition")
st.markdown("---")

col1, col2 = st.columns([1, 1])
audit_summary = []

with col1:
    st.markdown("### 🏠 家庭报税避坑测算")
    income = st.number_input("家庭年预计总收入 (MAGI)", value=150000)
    st.number_input("扶养人数 (Dependents)", value=1, min_value=0)
    st.button("保存测算结果 / Save Estimate")

with col2:
    st.markdown("### 📂 券商 1099 智能审计")
    uploaded_file = st.file_uploader("上传 1099 PDF 文件", type=['pdf'])
    
    if uploaded_file:
        # 这里是内容双语化的重点：定义更详细的英文+拼音对照
        st.warning("⚠️ Wash Sale Disallowed: $5,687.55")
        st.info("ℹ️ 1099-MISC Extra Income: $245.89")
        
        audit_summary = [
            "Wash Sale Risk (Xi Shou Feng Xian): $5,687.55 - HIGH RISK",
            "Extra Income (Qi Ta Shou Ru): $245.89 - Please Check 1099-MISC",
            "AI Tip (AI Jian Yi): Review Schedule D for potential tax savings."
        ]

st.markdown("---")
if st.button("📥 一键生成 PDF 结案报告 / Generate Report"):
    try:
        # 直接输出字节流，不再进行额外的编码转换，极致稳健
        pdf_out = create_pdf_report(income, audit_summary)
        st.download_button(
            label="点击下载报告 / Download PDF Report",
            data=bytes(pdf_out),
            file_name="Tax_Audit_Report_2026.pdf",
            mime="application/pdf"
        )
        st.success("✅ 报告生成成功 / Report Ready!")
    except Exception as e:
        st.error(f"Error: {str(e)}")